{{- if eq .Values.storage.provider "minio" }}
{{- $comp := dict "root" . "component" "minio" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentteams.minio.fullname" . }}
  namespace: {{ include "agentteams.namespace" . }}
  labels:
    {{- include "agentteams.component.labels" $comp | nindent 4 }}
{{- $svcType := .Values.storage.minio.service.type | default "ClusterIP" }}
spec:
  type: {{ $svcType }}
  {{- if eq $svcType "ClusterIP" }}
  clusterIP: None
  {{- end }}
  selector:
    {{- include "agentteams.component.selectorLabels" $comp | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.storage.minio.service.apiPort }}
      targetPort: api
      protocol: TCP
      {{- with .Values.storage.minio.service.apiNodePort }}
      nodePort: {{ . }}
      {{- end }}
    - name: console
      port: {{ .Values.storage.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
      {{- with .Values.storage.minio.service.consoleNodePort }}
      nodePort: {{ . }}
      {{- end }}
{{- end }}
