#!/usr/bin/env python3
"""Unified task-flow timeline for an OpenCode team (verification tool).

The room only shows the two ends of the collaboration (delegation and
TASK_COMPLETED); every intermediate step lives in a different medium. This
tool merges them into one chronological timeline so the full protocol can be
audited at a glance:

  ROOM      matrix traffic seen by the worker bridge (all senders, replies)
  BRIDGE    bridge turn lifecycle (turn start / agent.md / runtime actions)
  TASKFLOW  sandbox agentteams.log JSONL (ack / submit / status_change /
            verify / check_read / errors) — the authoritative task protocol
  META      MinIO meta.json state (assigned → in_progress → submitted with
            timestamps) and result.md presence
  LEADER    leader copaw.log agent-query boundaries (optional)

Usage (on the 105 server, from anywhere):

  SUDO_PASS='...' python3 watch_taskflow.py --worker ocw-1 --since 09:40
  SUDO_PASS='...' python3 watch_taskflow.py --worker ocw-1 --task hello-e2e2-...

Requires: kubectl (password via SUDO_PASS env, piped to sudo -S), mc on the
minio pod. Credentials never appear in output (mc lines are pre-redacted by
agentteams_log.py itself).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
from datetime import datetime, timezone

NS = "opencode-team-test"


def k(passw: str, *args: str, timeout: int = 30) -> str:
    proc = subprocess.run(
        ["sudo", "-S", "kubectl", *args],
        input=(passw + "\n").encode(),
        capture_output=True,
        timeout=timeout,
    )
    out = proc.stdout.decode("utf-8", "replace")
    if proc.returncode != 0 and not out.strip():
        raise RuntimeError(f"kubectl {' '.join(args[:3])} failed: {proc.stderr.decode()[:200]}")
    return out


def parse_since(value: str) -> datetime:
    now = datetime.now(timezone.utc)
    hhmm = re.fullmatch(r"(\d{1,2}):(\d{2})", value)
    if hhmm:
        cand = now.replace(hour=int(hhmm.group(1)), minute=int(hhmm.group(2)), second=0, microsecond=0)
        if cand > now:
            cand = cand.replace(day=cand.day - 1) if cand.day > 1 else cand
        return cand
    return datetime.fromisoformat(value).astimezone(timezone.utc)


def ts_of(iso: str) -> datetime:
    iso = iso.replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(iso).astimezone(timezone.utc)
    except ValueError:
        return datetime.now(timezone.utc)


ROOM_MSG = re.compile(r"matrix message room=\S+ sender=(\S+) event=(\S+) accepted=(\S+) role=\S+ reason=\S+ mentions=\[[^\]]*\] body='(.*)'$")
REPLY_MSG = re.compile(r"reply sent room=\S+ event_id=(\S+) bytes=\d+ body='(.*)'$")
TURN_LINE = re.compile(r"(turn start|turn completed) event_id=\S+(?: elapsed=([\d.]+)s)?")
AGENTMD_LINE = re.compile(r"agent\.md generated bytes=(\d+) sha256=\w+ wrote=(\S+)")
ACTION_LINE = re.compile(r"opencode action: (push agent\.md|reuse session|created session|post message|turn finished)\b[^|]*?(?:reply=|elapsed=([\d.]+)s)?.*$")


def bridge_events(passw: str, pod: str, since: datetime) -> list[tuple[datetime, str, str]]:
    """Room + bridge-lifecycle lines from the worker pod log (no timestamps in
    log lines themselves, so we bracket by pod-log --since-time; events are
    re-ordered later only within the same source)."""
    lines: list[tuple[datetime, str, str]] = []
    since_iso = since.strftime("%Y-%m-%dT%H:%M:%SZ")
    raw = k(passw, "logs", "-n", NS, pod, f"--since-time={since_iso}", "--timestamps=true")
    for ln in raw.splitlines():
        m = re.match(r"^(\S+)\s+(.*)$", ln)
        if not m:
            continue
        when, payload = ts_of(m.group(1)), m.group(2)
        mm = ROOM_MSG.search(payload)
        if mm:
            sender = mm.group(1).split(":")[0][1:]
            body = mm.group(4)[:160]
            tag = "ROOM←" if mm.group(3) == "True" else "room·"
            lines.append((when, f"{tag}{sender}", body))
            continue
        mr = REPLY_MSG.search(payload)
        if mr:
            lines.append((when, "ROOM→reply", mr.group(2)[:200]))
            continue
        if "INFO:cimicode_bridge" not in payload:
            continue
        if "turn start" in payload:
            lines.append((when, "BRIDGE", "turn start (mention accepted, entering runtime)"))
        elif "agent.md generated" in payload:
            ma = AGENTMD_LINE.search(payload)
            if ma:
                lines.append((when, "BRIDGE", f"agent.md {ma.group(1)}B → {ma.group(2)}"))
        elif "opencode action:" in payload:
            detail = payload.split("opencode action: ")[1].split(" user_message=")[0].split(" reply=")[0]
            lines.append((when, "BRIDGE", f"runtime: {detail[:120]}"))
        elif "turn completed" in payload:
            mt = TURN_LINE.search(payload)
            elapsed = mt.group(2) if mt and mt.group(2) else "?"
            lines.append((when, "BRIDGE", f"turn completed ({elapsed}s)"))
    return lines


def taskflow_events(passw: str, sandbox_pod: str, since: datetime, task_filter: str) -> list[tuple[datetime, str, str]]:
    out: list[tuple[datetime, str, str]] = []
    raw = k(passw, "exec", "-n", NS, sandbox_pod, "--", "cat", "/workspace/logs/agentteams.log")
    for ln in raw.splitlines():
        ln = ln.strip()
        if not ln:
            continue
        try:
            d = json.loads(ln)
        except json.JSONDecodeError:
            continue
        when = ts_of(d.get("ts", ""))
        if when < since:
            continue
        ev = d.get("event", "")
        task = d.get("task", "")
        if task_filter and task and task_filter not in task:
            continue
        if ev == "cmd_start":
            argv = d.get("argv", [])
            out.append((when, "TASKFLOW", f"$ taskflow {' '.join(map(str, argv))}"))
        elif ev == "status_change":
            out.append((when, "TASKFLOW", f"state {d.get('from')} → {d.get('to')}{'' if not d.get('result_status') else ' (result=' + str(d.get('result_status')) + ')'}"))
        elif ev == "pull":
            out.append((when, "TASKFLOW", "pull task dir from shared storage"))
        elif ev == "push":
            out.append((when, "TASKFLOW", "push task dir to shared storage"))
        elif ev == "verify":
            out.append((when, "TASKFLOW", f"verify {d.get('target','')} present on storage"))
        elif ev == "check_read":
            out.append((when, "TASKFLOW", f"check (read-only): status={d.get('status')} result={d.get('result')}"))
        elif ev == "error":
            out.append((when, "TASKFLOW!", f"error: {str(d.get('error'))[:140]}"))
        elif ev == "cmd_end":
            out.append((when, "TASKFLOW", f"exit={d.get('exit')} in {d.get('duration_ms')}ms"))
    return out


def meta_events(passw: str, minio_pod: str, since: datetime, task_filter: str) -> list[tuple[datetime, str, str]]:
    out: list[tuple[datetime, str, str]] = []
    listing = k(passw, "exec", "-n", NS, minio_pod, "--", "/usr/bin/mc", "ls", "--recursive",
                "local/agentteams-storage/teams/oct-team/shared/tasks/")
    for line in listing.splitlines():
        m = re.match(r"\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) UTC\]\s+(\S+)\s+\S+\s+(\S+)$", line.strip())
        if not m:
            continue
        when = datetime.strptime(m.group(1), "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
        size = m.group(2)
        key = m.group(3)
        if task_filter and task_filter not in key:
            continue
        if when < since:
            continue
        if key.endswith("meta.json"):
            raw = k(passw, "exec", "-n", NS, minio_pod, "--", "/usr/bin/mc", "cat",
                    f"local/agentteams-storage/teams/oct-team/shared/tasks/{key}")
            try:
                meta = json.loads(raw)
            except json.JSONDecodeError:
                continue
            stamps = [f"assigned={str(meta.get('assigned_at',''))[11:19]}"]
            if meta.get("acknowledged_at"):
                stamps.append(f"ack={meta['acknowledged_at'][11:19]}")
            if meta.get("submitted_at"):
                stamps.append(f"submit={meta['submitted_at'][11:19]}")
            out.append((when, "META", f"status={meta.get('status')} ({' '.join(stamps)})"))
        elif key.endswith(("spec.md", "result.md", ".txt", ".md", ".json", ".py", ".js", ".css", ".html")):
            out.append((when, "S3", f"{key.split('/')[-2]}/{key.split('/')[-1]} ({size})"))
    return out


def leader_events(passw: str, leader_pod: str, since: datetime) -> list[tuple[datetime, str, str]]:
    out = []
    raw = k(passw, "exec", "-n", NS, leader_pod, "--", "cat",
            "/root/.copaw-worker/oct-lead/.copaw/copaw.log", timeout=60)
    for ln in raw.splitlines():
        m = re.match(r"^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \| INFO \| .* \| (Handle agent query|Saved session state)", ln)
        if not m:
            continue
        when = datetime.strptime(m.group(1), "%Y-%m-%d %H:%M:%S").replace(tzinfo=timezone.utc)
        if when < since:
            continue
        out.append((when, "LEADER", "agent query start" if "Handle" in m.group(2) else "session saved (turn done)"))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--worker", default="ocw-1", help="worker name (default ocw-1)")
    ap.add_argument("--since", required=True, help="UTC HH:MM or ISO datetime")
    ap.add_argument("--task", default="", help="substring filter on task id")
    args = ap.parse_args()

    passw = os.environ.get("SUDO_PASS", "")
    if not passw:
        print("set SUDO_PASS env (server k3s sudo password)", file=sys.stderr)
        return 2
    since = parse_since(args.since)

    pods = k(passw, "get", "pods", "-n", NS, "-o", "name")
    def find(pat: str) -> str:
        for name in pods.splitlines():
            if pat in name:
                return name.split("/")[-1]
        raise RuntimeError(f"pod matching {pat} not found")

    worker_pod = find(f"agentteams-worker-{args.worker}")
    sandbox_pod = find(f"ocw-1-sandbox") if args.worker == "ocw-1" else find(f"{args.worker}-sandbox")
    minio_pod = find("minio")
    leader_pod = find("agentteams-worker-oct-lead")

    events: list[tuple[datetime, str, str]] = []
    events += bridge_events(passw, worker_pod, since)
    events += taskflow_events(passw, sandbox_pod, since, args.task)
    events += meta_events(passw, minio_pod, since, args.task)
    events += leader_events(passw, leader_pod, since)
    events.sort(key=lambda e: e[0])

    last_minute = ""
    for when, src, detail in events:
        hhmm = when.strftime("%H:%M")
        if hhmm[:4] != last_minute:
            print(f"\n── {when.strftime('%H:%M')} ──────────────────────")
            last_minute = hhmm[:4]
        print(f"  {when.strftime('%H:%M:%S')} {src:12} {detail}")
    if not events:
        print("(no events after since — check --since / --task filters)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
